<?php
/**
 * Default index controller generated by zend tool
 * @package default
 * @subpackage controllers
 * @version 1
 */
class Default_IndexController extends Zend_Controller_Action
{

    /**
     * (non-PHPdoc)
     * @see Zend_Controller_Action::init()
     */
    public function init()
    {
        /* Initialize action controller here */
    }

    /**
     * Index action for default controller
     */
    public function indexAction()
    {
        // action body
    }


}

