<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<article>

	<header>
		<h2>
			<?php echo $this->translate("CONTACT_CATEGORIES") ?>
		</h2>
	</header>
	
	<?php foreach ( $this->contacts as $contact ): ?>
	
	<div>
		<img src="<?php echo $this->baseUrl().'/upload/contact/'.$contact->image ?>" 
			alt="<?php echo $contact->image ?>" align="left" width="150px" />
		<span class="contactlabel"> <?php echo $this->translate("CONTACT_NAME") ?> </span>
		<span> <?php echo $contact->first_name. ' '.$contact->last_name ?> </span>
		<br />
		<span class="contactlabel"> <?php echo $this->translate("CONTACT_CON_POSITION") ?> </span>
		<span> <?php echo $contact->con_position ?> </span>
	</div>
	
	<?php endforeach; ?>
	
</article>