<script>
$(document).ready(function(){

	$('ul.nav').children().each( function(){
		if ( $(this).find('ul').length > 0 ) {
			$(this).addClass('dropdown');
			$(this).children('a').attr('data-toggle', 'dropdown');
			$(this).children('a').addClass('dropdown-toggle');
			$(this).children('a').append(' <b class="caret"></b>');
			$(this).find('ul').addClass('dropdown-menu');
			$(this).find('li').has('ul.dropdown-menu').each( function(){
				$(this).addClass('dropdown-submenu');
			});
		}
	});
	
});

</script>