<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<tr>
	<td class="field">
		<span class="field-title">
			<i class="icon-edit"></i>
			<a href='<?=$this->baseUrl()?>/contact/contact/edit/id/<?php echo $this->id; ?>'>
				<?php echo $this->first_name.' '.$this->last_name ?>
			</a>
		</span>
	</td>
	<td class="field">
		<i class="icon-edit"></i>
		<a href='<?=$this->baseUrl()?>/contact/contact/edit/id/<?php echo $this->category_id; ?>'>
			<?php echo $this->category_title ?>
		</a>
	</td>
	<td class="field">
		<?php echo $this->con_position ?>
	</td>
	<td class="center">
		<?php if( strlen($this->image) > 0 ) : ?>
		<?php 
			$imageParts = explode('.', $this->image);
			$imgName = current( $imageParts );
			$ext = end( $imageParts );
		?>
			<img src="<?php echo $this->baseUrl().'/upload/contact/thumbs/'.$imgName.'_thumb.'.$ext ?>" 
				alt="<?php echo $this->image ?>" />
		<?php endif; ?>
	</td>
	<td class="center">
		<?php if ( $this->published ): ?>
			<a href='<?=$this->baseUrl()?>/contact/contact/publish/id/<?php echo $this->id;?>' class="badge badge-success">
			<?php echo $this->translate("LBL_PUBLISHED") ?>
			</a>
		<?php else: ?>
			<a href='<?=$this->baseUrl()?>/contact/contact/publish/id/<?php echo $this->id;?>' class="badge badge-important">
			<?php echo $this->translate("LBL_UNPUBLISHED") ?>
			</a>
		<?php endif; ?>
	</td>
	<td class='center'>
		<a href='<?=$this->baseUrl()?>/contact/contact/move/direction/up/id/<?php echo $this->id; ?>'><?php echo $this->translate("LBL_MOVE_UP") ?></a>
		<span class="muted">|</span>
		<a href='<?=$this->baseUrl()?>/contact/contact/move/direction/down/id/<?php echo $this->id;?>'><?php echo $this->translate("LBL_MOVE_DOWN") ?></a>
		<span class="muted">|</span> 
	</td>
	<td>
		<i class="icon-trash"></i>
		<a href='<?=$this->baseUrl()?>/contact/contact/delete/id/<?php echo $this->id; ?>'><?php echo $this->translate("LBL_DELETE") ?></a>
	</td>
	<td class="center"><?php echo $this->ordering ?></td>
	<td class="center"><?php echo $this->id ?></td>
</tr>
