<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<script>
$(document).ready(function(){
	
	//$("#menuitem").attr("disabled","disabled");
	//var id = $("input[@name=testGroup]:checked").attr('id');
	$( $("#renderfor-0") ).click(
		function(){
			$("#menuitem").attr("disabled","disabled");
		}
	);
	$( $("#renderfor-1") ).click(
		function(){
			$("#menuitem").attr("disabled", false);
		}
	);
 });
</script>

<div class="page-header">
	<h2>
		<?php echo $this->widget->label ?>
		<small>
			<?php echo $this->widget->description ?>
		</small>
	</h2>
</div>

<div>
	<?php echo $this->frmWidget; ?>
</div>

