<div class="accordion" id="accordion_base">
	<div class="accordion-group">
		<!-- content header -->
		<div class="accordion-heading">
			<h4 class="accordion-toggle">
    			<?php echo $this->translate("ACL_RESET_PASSWORD") ?>
			</h4>
		</div>
		<!-- content body -->
		<div class="accordion-body in">
			<div class="accordion-inner">
				<?php echo $this->frmAccount ?>
			</div>
		</div>
	</div>
</div>
