<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<script src="<?php echo $this->getHelper('TemplateHelper')->getJSPath() ?>xdialog.js"></script>
<div class="accordion" id="accordion_base">
	<div class="accordion-group">
		<!-- content header -->
		<div class="accordion-heading">
			<h4 class="accordion-toggle"><?php echo $this->menu->name ?> <small><?php echo $this->translate("MENU_MANAGE_MENU_ITEMS") ?></small></h4>
		</div>
		<!-- content body -->
		<div class="accordion-body in">
			<div class="accordion-inner">
				
				<p>
        			<!--  <a href='<?php echo $this->baseUrl() ?>/menu/item/add/menu/<?php echo $this->menu->id ?>'> -->
        			<a href='<?php echo $this->baseUrl('menu-item-choose/'.$this->menu->id) ?>' class="btn">
        				<i class="icon-plus"></i>
        				<?php echo $this->translate("MENU_CREATE_MENUITEM") ?>
        			</a>
        		</p>
        		<div>
            		<?php if ($this->items->count()>0) : ?>
            		<table class="table table-bordered table-hover table-striped">
            			<thead>
            				<tr>
            					<th><?php echo $this->translate("LBL_TITLE") ?></th>
            					<th><?php echo $this->translate("ACL_MODULE") ?></th>
            					<th><?php echo $this->translate("ACL_CONTROLLER") ?></th>
            					<th><?php echo $this->translate("MENU_ACTION_PRIVILEGE") ?></th>
            					<th><?php echo $this->translate("MENU_ITEM_PARENT") ?></th>
            					<th><?php echo $this->translate("MENU_ITEM_WINDOW_TYPE") ?></th>
            					<th><?php echo $this->translate("MENU_ITEM_ID_ALIAS") ?></th>
            					<th><?php echo $this->translate("LBL_STATUS") ?></th>
            					<th></th>
            					<th><?php echo $this->translate("LBL_POSITION") ?></th>
            					<th>#</th>
            				</tr>
            			</thead>
            			<tbody>
            			<?php echo $this->partialLoop('partials/_menu-item-row.phtml', $this->items); ?>
            			</tbody>
            		</table>
            		<?php echo $this->paginationControl( $this->items, 'Sliding', 'pagination-control.phtml' ); ?>
            		<?php else : ?>
            		<p class="muted"><?php echo $this->translate("LBL_NO_ITEMS_REGISTERED_YET") ?></p>
            		<?php endif; ?>
            	</div>
            	
            	<div class="muted">Nro Items: <?php echo $this->rows->count() ?></div>
				
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$('.xdialog').click(function(e){
		e.preventDefault();
		$(this).xdialog({q:'Do you really want to remove it?'});
	});
});
</script>