<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<article>

	<div>
		<?php echo $this->frmArticle ?>
	</div>
	
</article>
<script type='text/javascript'>
$(document).ready(function(){
	// content
	$('#content').wysihtml5();
	$('#content').css('width', '600px');
	$('#content').css('height', '150px');
	$('#content').attr('placeholder', '<?php echo $this->translate('LBL_ENTER_TEXT') ?>');
	// introcontent
	$('#introcontent').wysihtml5();
	$('#introcontent').css('width', '600px');
	$('#introcontent').css('height', '150px');
	$('#introcontent').attr('placeholder', '<?php echo $this->translate('LBL_ENTER_TEXT') ?>');

});
</script>