<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<article>

	<div>
		<?php echo $this->frmContact ?>
	</div>
	
</article>

<div class="input-append" id="imagedetailcontainer" style="display: none;">
   <input id="image_description_path_helper" class="input-large" type="text">
   <a class="btn" onclick="$('input[id=image]').click();">Browse</a>
</div>

<script type="text/javascript">
$('#image').css('display', 'none');
$('input[id=image]').parent().append( $("#imagedetailcontainer").html() );
$('input[id=image]').change(function() {
   $('#image_description_path_helper').val($(this).val());
});
</script>
 