<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<?php if ( $this->identity ) : ?>
	<?php echo $this->translate("LBL_WELCOME").'! ' ?> &nbsp;
	<?php if( $this->identity->id < 3 ): ?> 
	<a href='<?php echo $this->baseUrl() ?>/update-account/'>
		<?php echo $this->identity->fullname ?>
	</a>
	<?php endif; ?>
    &nbsp;
	<a href='<?php echo $this->baseUrl() ?>/logout/'>
	    <i class="icon-off"></i>
		<?php #echo $this->translate("ACL_LOGOUT") ?>
	</a>
<?php else: ?>

<?php echo $this->frmLogin; ?>
<div class="control-group" id="rstpwd">
    <label class="control-label">&nbsp;</label>
	<div class="controls">
		<p><a href="<?php echo $this->baseUrl('resetpassword') ?>"><?php echo $this->translate('ACL_FORGET_PASSWORD') ?></a></p>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#frmlogin fieldset").append( $('#rstpwd').html() );
	$('#rstpwd').remove();
});
</script>
<?php endif; ?>
