<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<?php 
if ( $this->articles != null ) :
?>
<?php echo $this->partialLoop('partials/_row_category_articles_blog_layout.phtml', $this->articles); ?>
<?php else : ?>
<p><?php echo $this->translate("CONTENT_NO_ARTICLES_AVAILABLE_UNDER_THIS_CATEGORY") ?></p>
<?php endif; ?>