<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<div class="powered">
<?php echo $this->translate('LBL_POWERED_BY') ?> Zend Framework <?php echo $this->translate('LBL_AND') ?> OWLSys
<br>
OWLSys <?php echo $this->translate('LBL_IS_FREE_SOFTWARE_RELEASED_UNDER_THE') ?> <a href="http://www.gnu.org/licenses/gpl-3.0.html" target="_blank">GNU General Public License</a>
<br />
<?php echo $this->translate("LBL_DEVELOPED_BY") ?> <a href="mailto:rcastaneda@owlcompany.com.pe" target="_blank">Roger Casta&ntilde;eda</a> 
</div>