<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<?php
$modules = array(); 
foreach( $this->widgets as $wdigetType ) :
	$module = strval($wdigetType->module);
	if ( ! in_array($module, $modules) ) $modules[] = $module;
endforeach; 
?>
<article>
	<header>
		<h2><?php echo $this->translate('SYSTEM_CHOOSE_WIDGET_TYPE') ?></h2>
	</header>
	
	<div id="accordion" class="accordion">
	<?php $ind=1; ?>
	<?php foreach ( $modules as $module ): ?>
	<div class="accordion-group">
		<div class="accordion-heading">
			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $ind ?>">
			<?php echo $this->translate('ACL_MODULE').': '.ucfirst( strtolower($module) ) ?>
			</a>
		</div>
		<div id="collapse<?php echo $ind ?>" class="accordion-body collapse">
			<div class="accordion-inner">
			<?php foreach( $this->widgets as $widget ) : ?>
			<?php if ( $module == $widget->module ): ?>
				<p>
					<a href="<?php echo $this->baseUrl().'/system/widget/new/mod/'.$widget->module.'/wid/'.$widget['id'] ?>">
						<?php echo $widget->label ?>
					</a>
					<br>
					<span class="muted"><?php echo $widget->description ?></span>
				</p>
				<?php endif; ?>
			<?php endforeach; ?>
			</div>
		</div>
	</div>
	<?php $ind++ ?>
	<?php endforeach; ?>
	</div>
	
</article>
<script>
$(function() {
	$( "#accordion" ).accordion( { collapsible: true, active: false, autoHeight: false, } );
});
</script>
