<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
/* @var $skin System_Model_Skin */
$skin = $this->skin;
?>
<tr>
	<td class="field">
		<p class="info"><?php echo $skin->getName() ?></p>
		<span class="muted"><?php echo $skin->getDescription() ?></span>
	</td>
	<td class="center"><?php echo $skin->getAuthor() ?></td>
	<td class="center"><?php echo $skin->getLicense() ?></td>
	
	<td>
		<?php if ( $skin->getIsSelected() == 1 ): ?>
		  <a href="#" class="btn btn-mini btn-success">
			<i class="icon-ok icon-white"></i>
		  </a>
		<?php else: ?>
			<a href='<?=$this->baseUrl('skin-select/'.$skin->getId())?>' class="btn btn-mini">
				<i class="icon-screenshot icon-white"></i>
			</a>
		<?php endif; ?>
	</td>
	<td class="center"><?php echo $this->partialCounter ?></td>
</tr>
