<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
/* @var $widget System_Model_Widget */
$widget = $this->widget;
?>
<tr>
	<td class="field">
	    <?php echo $widget->getTitle() ?>
	</td>
	<td class="center"><?php echo $widget->getPosition() ?></td>
	<td class="center"><?php echo $widget->getOrdering() ?></td>
	<td class="field"><?php echo $widget->getResource()->getModule().' / '.$widget->getResource()->getController().' / '.$widget->getResource()->getActioncontroller() ?></td>
	<td class="center">
		<?php if ( $widget->getIsPublished() == 1 ): ?>
			<a href='<?=$this->baseUrl('widget-publish/'.$widget->getId())?>' class="btn btn-mini btn-success">
			 <i class="icon-ok-circle icon-white"></i>
			</a>
		<?php else: ?>
			<a href='<?=$this->baseUrl('widget-publish/'.$widget->getId())?>' class="btn btn-mini btn-danger">
			 <i class="icon-remove-circle icon-white"></i>
			</a>
		<?php endif; ?>
	</td>
	<td class='center'>
	    <div class="btn-group">
    	    <a href='<?=$this->baseUrl('widget-update/'.$widget->getId())?>' title="<?php echo $this->translate("Edit").' '.$widget->getTitle() ?>" class="btn btn-mini">
    		    <i class="icon-edit"></i>
    		</a>
    		<a href='<?=$this->baseUrl('widget-move/'.$widget->getId().'/up')?>' class="btn btn-mini">
    		    <i class="icon-chevron-up"></i>
    		</a>
    		<a href='<?=$this->baseUrl('widget-move/'.$widget->getId().'/down')?>' class="btn btn-mini">
    		    <i class="icon-chevron-down"></i>
    		</a>
    		<a href='<?=$this->baseUrl('widget-delete/'.$widget->getId())?>' class="btn btn-mini xdialog">
    		    <i class="icon-trash"></i>
    		</a>
		</div>
	</td>
	<td class="center"><?php echo $this->partialCounter ?></td>
</tr>
