<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<tr>
	<td class="field">
		<span class="text-info"><?php echo $this->title ?></span>
		<?php if ( strlen($this->description) > 0 ) : ?>
			<br />
			<span class="muted"><?php echo $this->description ?></span>
			<br />
		<?php endif; ?>
	</td>
	<td class="center">
		<?php echo $this->module ?>
	</td>
	<td class="center">
		<?php echo $this->controller ?>
	</td>
	<td class="center">
		<?php echo $this->actioncontroller ?>
	</td>
	<td class="center">
		<?php echo $this->titleParent ?>
	</td>
	<td class="center">
		<?php echo $this->wtype ?>
	</td>
	<td class="center">
		<?php echo $this->id_alias ?>
	</td>
	<td class="center">
		<?php if ( $this->published ): ?>
			<a href='<?=$this->baseUrl()?>/menu/item/publish/id/<?php echo $this->id;?>' class="badge badge-success">
			<?php echo $this->translate("LBL_PUBLISHED") ?>
			</a>
		<?php else: ?>
			<a href='<?=$this->baseUrl()?>/menu/item/publish/id/<?php echo $this->id;?>' class="badge badge-important">
			<?php echo $this->translate("LBL_UNPUBLISHED") ?>
			</a>
		<?php endif; ?>
	</td>
	<td class='links field'>
		<a href='<?=$this->baseUrl()?>/menu/item/update/id/<?php echo $this->id; ?>'><i class="icon-edit"></i><?php echo $this->translate("LBL_UPDATE") ?></a>
		<span class="muted">|</span> 
		<a href='<?=$this->baseUrl()?>/menu/item/move/direction/up/id/<?php echo $this->id; ?>'><i class="icon-chevron-up"></i><?php #echo $this->translate("LBL_MOVE_UP") ?></a>
		<span class="muted">|</span>  
		<a href='<?=$this->baseUrl()?>/menu/item/move/direction/down/id/<?php echo $this->id;?>'><i class="icon-chevron-down"></i><?php #echo $this->translate("LBL_MOVE_DOWN") ?></a>
		<span class="muted">|</span>
		<a href='<?=$this->baseUrl()?>/menu/item/delete/id/<?php echo $this->id; ?>'><i class="icon-trash"></i><?php #echo $this->translate("LBL_DELETE") ?></a>
	</td>
	<td class="center"><?php echo $this->ordering ?></td>
	<td class="center"><?php echo $this->id ?></td>
</tr>
