<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<div id="accordion" class="accordion">
<?php $ind=1; ?>
<?php foreach ( $this->modules as $module ) : ?>
	<div class="accordion-group">
		<div class="accordion-heading">
			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $ind ?>">
			<?php echo $module->title ?>
			</a>
		</div>
		<div id="collapse<?php echo $ind ?>" class="accordion-body collapse">
			<div class="accordion-inner">
				<p>
					<span class="text-info"><?php echo $module->description ?></span><br />
					<b>Version:</b> <span class="text-warning"><?php echo $module->version ?></span><br />
					<b>Author:</b> <span class="text-warning"><?php echo $module->author ?></span><br />
					<b>License:</b> <span class="muted"><?php echo $module->license ?></span><br />
				</p>
			</div>
		</div>
	</div>
	<?php $ind++ ?>
<?php endforeach; ?>
</div>
<script>

</script>