<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
/* @var $account Acl_Model_Account */
$account = $this->account;
?>
<tr>
	<td><?php echo $account->email ?></td>
	<td class="center"><?php echo $account->role ?></td>
	<td class="center"><?php echo $account->registerdate ?></td>
	<td class="center"><?php echo $account->lastvisitdate ?></td>
	<td class="center">
		<?php if ( $account->isBlocked ): ?>
		<a href='<?=$this->baseUrl('account-block/'.$account->id)?>' class="btn btn-mini btn-danger">
			<?php echo $this->translate("Blocked") ?>
		</a>
		<?php else: ?>
		<a href='<?=$this->baseUrl('account-block/'.$account->id)?>' class="btn btn-mini btn-success">
			<?php echo $this->translate("Unblocked") ?>
		</a>
		<?php endif; ?>
	</td>
	<td class="center">
		<a href='<?=$this->baseUrl('account/update/'.$account->id)?>' class="btn btn-mini btn-warning">
		    <i class="icon-edit icon-white"></i>
		</a>
		<?php if ( $account->id > 1 ) : ?>
		<a href='<?=$this->baseUrl('account-delete/'.$account->id)?>' class="btn btn-mini xdialog">
		    <i class="icon-trash"></i>
		</a>
		<?php endif; ?>
	</td>
	<td class="center"><?php echo $this->partialCounter ?></td>
</tr>