<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
/* @var $role Acl_Model_Role */
$role = $this->role;
?>
<tr>
	<td class="field"><?php echo $role->name ?></td>
	<td class="center"><?php echo $role->layout_name ?></td>
	<td class="center">
		<?php #if ( $this->id != 1 ) : ?>
		<a href='<?=$this->baseUrl('permissions-manager/'.$role->id)?>' class="btn btn-mini">
		    <i class="icon-list"></i>
			<?php echo $this->translate("Privileges") ?>
		</a>
		<?php #endif; ?>
	</td>
	<td class="center">
		<?php if ( $role->id > 1 ) : ?>
		 
		<a href='<?=$this->baseUrl('role-update/'.$role->id)?>' class="btn btn-mini">
			<i class="icon-edit"></i>
			<?php echo $this->translate('Edit') ?>
		</a>
		<?php endif; ?>
		<?php if ( $role->id > 3 ) : ?>
		<a href='<?=$this->baseUrl('role-delete/'.$role->id)?>' class="btn btn-mini xdialog">
			<i class="icon-trash"></i>
		</a>
		<?php endif; ?>
	</td>
	<td class="center"><?php echo $this->partialCounter ?></td>
</tr>