<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
/* @var $resource Acl_Model_Resource */
$resource = $this->resource;
?>
<tr>
	<td><?php echo $resource->getModule() ?></td>
	<td><?php echo $resource->getController() ?></td>
	<td><?php echo $resource->getActioncontroller() ?></td>
	<td class="center">
		<a href='<?=$this->baseUrl('resource-delete/'.$resource->getId())?>' class="btn btn-mini btn-danger xdialog">
			<i class="icon-trash icon-white"></i>
			<?php echo $this->translate('Remove') ?>
		</a>
	</td>
	<td class="center"><?php echo $this->partialCounter ?></td>
</tr>