<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<tr>
	<td class="field"><?php echo $this->name ?></td>
	<td class="field"><?php echo $this->parent_name ?></td>
	<td class="center"><?php echo $this->priority ?></td>
	<td class="center">
		<?php #if ( $this->id != 1 ) : ?>
		<i class="icon-list"></i> 
		<a href='<?=$this->baseUrl()?>/acl/permission/manage/role/<?php echo $this->id;?>'>
			<?php echo $this->translate("ACL_MANAGE_PERMISSIONS") ?>
		</a>
		<?php #endif; ?>
	</td>
	<td class="center">
		<?php if ( $this->id > 3 ) : ?>
		<i class="icon-edit"></i> 
		<a href='<?=$this->baseUrl()?>/acl/role/update/id/<?php echo $this->id;?>'>
			<?php echo $this->translate("LBL_UPDATE") ?>
		</a>
		<?php endif; ?>
	</td>
	<td class="center">
		<?php if ( $this->id > 3 ) : ?>
		<i class="icon-trash"></i> 
		<a href='<?=$this->baseUrl()?>/acl/role/delete/id/<?php echo $this->id;?>'>
			<?php echo $this->translate("LBL_DELETE") ?>
		</a>
		<?php endif; ?>
	</td>
	<td class="center"><?php echo $this->id ?></td>
</tr>