<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<tr>
	<td><?php echo $this->module ?></td>
	<td><?php echo $this->controller ?></td>
	<td><?php echo $this->actioncontroller ?></td>
	<td class="center">
		<a href='<?=$this->baseUrl()?>/acl/resource/delete/id/<?php echo $this->id;?>'>
			<i class="icon-trash"></i>
			<?php echo $this->translate("LBL_DELETE") ?>
		</a>
	</td>
	<td class="center"><?php echo $this->id ?></td>
</tr>