<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>


	<h2><?php echo $this->translate("ACL_MANAGE_RESOURCES") ?></h2>
	<p>
		<a href='<?php echo $this->baseUrl() ?>/acl/resource/sync/' class="btn">
			<i class="icon-refresh"></i>
			<?php echo $this->translate("ACL_SYNC_RESOURCES") ?>
		</a>
	</p>
	
	<div>
		<?php 
		if ( $this->resources != null || count($this->resources) > 0 ) :
		?>
			<table class="table table-bordered table-hover table-striped">
				<thead>
					<tr>
						<th><?php echo $this->translate("ACL_MODULE") ?></th>
						<th><?php echo $this->translate("ACL_CONTROLLER") ?></th>
						<th><?php echo $this->translate("ACL_ACTION") ?></th>
						<th><?php echo $this->translate("LBL_DELETE") ?></th>
						<th>#</th>
					</tr>
				</thead>
				<tbody>
				<?php echo $this->partialLoop('partials/_row_resource.phtml', $this->resources); ?>
				</tbody>
			</table>
		<?php else : ?>
		<p class="muted"><?php echo $this->translate("LBL_NO_ITEMS_REGISTERED_YET") ?></p>
		<?php endif; ?>
		<?php echo $this->paginationControl( $this->resources, 'Sliding', 'pagination-control.phtml' ); ?>
	</div>



