<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<?php if ( $this->identity ) : ?>
	<?php echo $this->translate("LBL_WELCOME").'! ' ?> &nbsp; 
	<a href='<?php echo $this->baseUrl() ?>/acl/account/update/'>
		<?php echo $this->identity->email ?>
	</a> 
	<br />
	<i class="icon-off"></i>
	<a href='<?php echo $this->baseUrl() ?>/acl/authentication/logout/'>
		<?php echo $this->translate("ACL_LOGOUT") ?>
	</a>
<?php else: ?>
<article>
	<div>
		<?php echo $this->frmLogin; ?>
	</div>
</article>
<?php endif; ?>
