<?php
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details. 
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */ 
echo $this->doctype();
$this->headMeta ()->appendHttpEquiv ( 'Content-Type', 'text/html;charset=utf-8' );
$this->headMeta()->appendName('viewport',"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no");
$this->headMeta()->appendName('X-UA-Compatible',"IE=edge,chrome=1");
?>
<html>
<head>
    <?php
	$this->headScript()->prependFile("//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js");
	echo $this->headMeta ();
	echo $this->headTitle ();
	echo $this->headLink();
	echo $this->headScript();
	?>
</head>

<body>

	
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="brand" href="javascript:void(0);">CONALUD</a>
                <div class="nav-collapse">
                <?php echo $this->layout ()->pos_admin_mainmenu; ?>
                </div>
                <div class="navbar-text pull-right">
                    <?php echo $this->layout()->pos_admin_top_right; ?>
                </div>
            </div>
        </div>
    </div>
    
    <div class="cleafix" style="margin-top: 60px;"></div>
    
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
            
                <div class="row-fluid">
                    <?php echo $this->layout ()->breadcrumb; ?>
        	    </div>
        	    
        	    <div class="row-fluid">
    				<?php if( strlen( $this->flashMessages()) > 0 ): ?>
    				<div class="span12">
    				<?php echo $this->flashMessages() ?>
    				</div>
    				<?php endif; ?>
        	    </div>
        	    
        	    <div class="row-fluid">
        	        <div class="span12">
        				<div class="content">
        					<?php echo $this->layout ()->content; ?>
        				</div>
        			</div>
        	    </div>
            
            </div>
        </div>
    
	    <div class="row-fluid">
	        <hr>
            <footer>
        		<p>&copy; CONALUD 2013 | Powered by <a href="http://rogercastaneda.com" target="_blank">rogercastaneda.com</a></p>
        	</footer>
	    </div>
	    
    </div>
    
    <?php #echo $this->headScript(); ?>
    
    <?php echo $this->render('includes/profiler.phtml') ?>
	
</body>
</html>