<?php
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
echo $this->doctype();
$this->headMeta ()->appendHttpEquiv ( 'Content-Type', 'text/html;charset=utf-8' );
$this->headMeta()->appendName('viewport',"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no");
$this->headMeta()->appendName('X-UA-Compatible',"IE=edge,chrome=1");
?>
<html>
<head>
    <?php
		# jquery
        $this->headScript()->prependFile("//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js");
	    /*if ( $this->jQuery()->isEnabled() ) {
	    	$this->jQuery()
		    	->setLocalPath( $this->baseUrl()."/jquery/js/jquery-1.7.2.min.js" )
		    	->setUiLocalPath( $this->baseUrl()."/jquery/js/jquery-ui-1.8.12.custom.min.js" )
		    	->addStylesheet( $this->baseUrl()."/jquery/css/ui-lightness/jquery-ui-1.8.20.custom.css" );
	    	echo $this->jQuery();
	    }
		# modernizr
		$this->headScript()->appendFile( $this->baseUrl().'/js/modernizr.custom.99420.js');
		# system default script required 
		$this->headScript()->appendFile( $this->baseUrl().'/js/system.js');
		# mod content
		$this->headScript()->appendFile( $this->baseUrl().'/js/mod_content.js');
		# main css
		$this->headLink()->prependStylesheet($this->baseUrl().'/css/mobile.css');
		# favicon
		$this->headLink()->headLink( array('rel' => 'favicon', 'href' => $this->baseUrl().'/favicon.ico'), 'PREPEND');
		*/
    	#$this->headScript()->prependFile('http://code.jquery.com/jquery-latest.js');
    	
		echo $this->headMeta ();
		echo $this->headTitle ();
		echo $this->headLink();
		echo $this->headScript();
		
	?>
</head>

<body>
	
	<div class="container-narrow">

      <div class="masthead">
        <?php echo $this->layout()->menu_top; ?>
        <h3 class="muted">CONALUD</h3>
      </div>
      
      <hr>
      
      <div class="row-fluid">
        <?php #if( strlen( $this->flashMessages()) > 0 ): ?>
    	    <?php echo $this->flashMessages() ?>
		<?php #endif; ?>
		<div class="content">
			<?php echo $this->layout ()->content; ?>
		</div>
      </div>
      
    </div>

	<div class="container-narrow">
		<div class="footer">
			<p>&copy; CONALUD 2013 | Powered by <a href="http://rogercastaneda.com" target="_blank">rogercastaneda.com</a></p>
		</div>
	</div>
</body>
</html>