<?php
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
echo $this->doctype();
$this->headMeta ()->appendHttpEquiv ( 'Content-Type', 'text/html;charset=utf-8' );
$this->headMeta()->appendName('viewport',"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no");
$this->headMeta()->appendName('X-UA-Compatible',"IE=edge,chrome=1");
#$this->headTitle ()->setSeparator ( ' - ' );
#$this->headTitle ( 'Some title' );
?>
<html>
<head>
<?php
    $this->headScript()->prependFile("//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js");
	echo $this->headMeta ();
	echo $this->headTitle ();
	echo $this->headLink();
	echo $this->headScript();
?>
    <style>
        body {padding-top: 20px;padding-bottom: 40px;}
        /* Custom container */
        .container-narrow {margin: 0 auto;max-width: 700px;}
        .container-narrow>hr {margin: 30px 0;}
        label { font-size: 12px; }
	</style>
</head>

<body>

    <div class="container">

      <div class="masthead">
        <?php echo $this->layout()->menu_top; ?>
        <h3 class="muted">OWLSys</h3>
      </div>
      
      <hr>
      
      <div class="row">
        <div class="span12">
        <?php #if( strlen( $this->flashMessages()) > 0 ): ?>
    	    <?php echo $this->flashMessages() ?>
		<?php #endif; ?>
		</div>
		<div class="span12">
    		<div class="content">
    			<?php echo $this->layout ()->content; ?>
    		</div>
		</div>
      </div>
      
      <div class="row">
        <div class="span12">
            <div class="footer">
    			<p>&copy; OWLSys 2013 | Powered by <a href="http://rogercastaneda.com" target="_blank">rogercastaneda.com</a></p>
    		</div>
        </div>
      </div>
      
    </div>

	<?php #echo $this->render('includes/profiler.phtml') ?>
	
</body>
</html>