<h1>OWLSys</h1>
<div class="powered">
<?php echo $this->translate('LBL_POWERED_BY') ?> Zend Framework <?php echo $this->translate('LBL_AND') ?> OWLSys
<br>
OWLSys <?php echo $this->translate('LBL_IS_FREE_SOFTWARE_RELEASED_UNDER_THE') ?> <a href="http://www.gnu.org/licenses/gpl-3.0.html" target="_blank">GNU General Public License</a>
<br />
<?php echo $this->translate("LBL_DEVELOPED_BY") ?> <a href="mailto:info@rogercastaneda.com" target="_blank">Roger Casta&ntilde;eda</a> 
</div>