<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
/* @var $menuItem menu_Model_Item */
$menuItem = $this->menuItem;
?>
<tr>
	<td class="field">
		<span class="text-info"><?php echo $menuItem->getTitle() ?></span>
		<?php if ( strlen($menuItem->getDescription()) > 0 ) : ?>
			<br />
			<span class="muted"><?php echo $menuItem->getDescription() ?></span>
			<br />
		<?php endif; ?>
	</td>
	<td class="center">
		<?php echo $menuItem->getResource()->getModule() ?>
	</td>
	<td class="center">
		<?php echo $menuItem->getResource()->getController() ?>
	</td>
	<td class="center">
		<?php echo $menuItem->getResource()->getActioncontroller() ?>
	</td>
	<td class="center">
		<?php echo $menuItem->getParent()->getTitle() ?>
	</td>
	<td class="center">
		<?php echo $menuItem->getWtype() ?>
	</td>
	<td class="center">
		<?php echo $menuItem->getRoute() ?>
	</td>
	<td class="center">
		<?php if ( $menuItem->getIsPublished() == 1 ): ?>
			<a href='<?=$this->baseUrl('menu-item-publish/'.$menuItem->getId())?>' class="btn btn-mini btn-success">
			<i class="icon-ok-circle icon-white"></i>
			</a>
		<?php else: ?>
			<a href='<?=$this->baseUrl('menu-item-publish/'.$menuItem->getId())?>' class="btn btn-mini btn-danger">
			<i class="icon-remove-circle icon-white"></i>
			</a>
		<?php endif; ?>
	</td>
	<td class=''>
	    <div class="btn-group">
    		<a href='<?=$this->baseUrl('menu-item-update/'.$menuItem->getId())?>' class="btn btn-mini"><i class="icon-edit"></i></a>
    		<a href='<?=$this->baseUrl('menu-item-move/up/'.$menuItem->getId())?>' class="btn btn-mini"><i class="icon-chevron-up"></i></a>
    		<a href='<?=$this->baseUrl('menu-item-move/down/'.$menuItem->getId())?>' class="btn btn-mini"><i class="icon-chevron-down"></i></a>
    		<a href='<?=$this->baseUrl('menu-item-delete/'.$menuItem->getId())?>' class="btn btn-mini xdialog"><i class="icon-trash"></i></a>
		</div>
	</td>
	<td class="center"><?php echo $menuItem->getOrdering() ?></td>
	<td class="center"><?php echo $this->partialCounter ?></td>
</tr>
