<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
/* @var $menu menu_Model_Menu */
$menu = $this->menu;
?>
<tr>
	<td class="field"><?php echo $menu->getName() ?></td>
	<td class="center">
		<?php if ( $menu->getIsPublished() ): ?>
			<a href='<?=$this->baseUrl('menu-publish/'.$menu->getId())?>' class="btn btn-mini btn-success">
				<i class="icon-ok-circle icon-white"></i>
			</a>
		<?php else: ?>
			<a href='<?=$this->baseUrl('menu-publish/'.$menu->getId())?>' class="btn btn-mini btn-danger">
				<i class="icon-remove-circle icon-white"></i>
			</a>
		<?php endif; ?>
	</td>
	<td class="center">
		<a href='<?=$this->baseUrl('menu-items/'.$menu->getId())?>' class="btn btn-mini"><?php echo $this->translate("Manage menu items") ?></a>
	</td>
	<td class="center">
		<a href='<?=$this->baseUrl('menu-update/'.$menu->getId())?>' title="<?php echo $this->translate("Edit") ?>" class="btn btn-mini">
		    <i class="icon-edit"></i>
		</a>
		<a href='<?=$this->baseUrl('menu-delete/'.$menu->getId())?>' title="<?php echo $this->translate("Remove") ?>" class="btn btn-mini xdialog">
		    <i class="icon-trash"></i>
		</a>
	</td>
	<td class="center"><?php echo $this->partialCounter ?></td>
</tr>