<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<script src="<?php echo $this->getHelper('TemplateHelper')->getJSPath() ?>xdialog.js"></script>
<div class="accordion" id="accordion_base">
	<div class="accordion-group">
		<!-- content header -->
		<div class="accordion-heading">
			<h4 class="accordion-toggle"><?php echo $this->translate("Menus") ?></h4>
		</div>
		<!-- content body -->
		<div class="accordion-body in">
			<div class="accordion-inner">
				<p>
        			<a href='<?php echo $this->baseUrl('menu-create') ?>' class="btn btn-small">
        				<i class="icon-plus"></i>
        				<?php echo $this->translate("New Menu") ?>
        			</a>
        		</p>
        		<div>
            		<?php if ( count($this->menus) > 0 ) : ?>
            			<table class="table table-bordered table-hover table-striped">
            				<thead>
            				<tr>
            					<th><?php echo $this->translate("Title") ?></th>
            					<th><?php echo $this->translate("Published") ?></th>
            					<th><?php echo $this->translate("Manage menu items") ?></th>
            					<th>&nbsp;</th>
            					<th>#</th>
            				</tr>
            				</thead>
            				<tbody>
            				<?php 
                    		  echo $this->partialLoop()
                        		  ->setObjectKey('menu')
                        		  ->partialLoop('partials/_row_menu.phtml', $this->menus) 
                    		?>
            				</tbody>
            			</table>
            			<?php echo $this->paginationControl( $this->menus, 'Sliding', 'pagination-control.phtml', array('route'=>'menus') ); ?>
            		<?php else : ?>
            		<p class="muted"><?php echo $this->translate("No registered items") ?></p>
            		<?php endif; ?>
            	</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	$('.xdialog').click(function(e){
		e.preventDefault();
		$(this).xdialog({q:'<?php echo $this->translate("Do you really want to remove it?") ?>'});
	});
});
</script>