<?php 
/**
 * Copyright 2012 Roger Castañeda
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
?>
<h2>ACL Module &rsaquo;</h2>

<h3>:: Account </h3>

<a href="<?php echo $this->baseUrl(); ?>/acl/account/list">List accounts</a> |
<a href="<?php echo $this->baseUrl(); ?>/acl/account/create">Create new account</a>
<br /><br />

<h3>:: Resource </h3>
<a href="<?php echo $this->baseUrl(); ?>/acl/resource/list">List Resources</a> |
<a href="<?php echo $this->baseUrl(); ?>/acl/resource/loadrde">Load Resource Data Enviroment</a> 

<br /><br />
<h3>:: Role </h3>
<a href="<?php echo $this->baseUrl(); ?>/acl/role/list">List Roles</a> |
<a href="<?php echo $this->baseUrl(); ?>/acl/role/create">Create new role</a> 